title: Syaning

date_format: "%Y-%m-%d"

google_analytics: UA-56203680-1
disqus_shortname: zztf

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty

# gems
gems:
  - jekyll-feed
